[tool.poetry]
name = "ferias-libres-data"
version = "0.1.0"
description = "Archivos de datos para Ferias Libres"
authors = ["Mario Hernandez <mariofix@pm.me>"]
license = "MIT"
readme = "README.md"
packages = [{include = "ferias_libres_data"}]

[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.24.0"
typer = {extras = ["all"], version = "^0.9.0"}
pydantic-settings = "^1.99"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
