"""slug

Revision ID: 1c4a244f8317
Revises: 626f6db311db
Create Date: 2023-07-05 03:43:34.711882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "1c4a244f8317"
down_revision = "626f6db311db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ferias_feria", schema=None) as batch_op:
        batch_op.alter_column(
            "slug", existing_type=mysql.VARCHAR(length=64), type_=sa.String(length=128), existing_nullable=False
        )
        batch_op.alter_column(
            "nombre", existing_type=mysql.VARCHAR(length=64), type_=sa.String(length=128), existing_nullable=False
        )
        batch_op.drop_index("uq_ferias_feria_slug")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ferias_feria", schema=None) as batch_op:
        batch_op.create_index("uq_ferias_feria_slug", ["slug"], unique=False)
        batch_op.alter_column(
            "nombre", existing_type=sa.String(length=128), type_=mysql.VARCHAR(length=64), existing_nullable=False
        )
        batch_op.alter_column(
            "slug", existing_type=sa.String(length=128), type_=mysql.VARCHAR(length=64), existing_nullable=False
        )

    # ### end Alembic commands ###
