"""slug unique

Revision ID: 22d0cdc5c886
Revises: 1c4a244f8317
Create Date: 2023-07-05 03:53:56.726128

"""
import sqlalchemy as sa  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision = "22d0cdc5c886"
down_revision = "1c4a244f8317"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ferias_feria", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_ferias_feria_slug"), ["slug"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ferias_feria", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_ferias_feria_slug"), type_="unique")

    # ### end Alembic commands ###
