"""Init

Revision ID: 771a438591c5
Revises:
Create Date: 2023-06-21 01:51:54.889780

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "771a438591c5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_role")),
        sa.UniqueConstraint("name", name=op.f("uq_security_role_name")),
    )
    op.create_table(
        "security_roles_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["security_role.id"],
            name=op.f("fk_security_roles_users_role_id_security_role"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["firenze_user.id"],
            name=op.f("fk_security_roles_users_user_id_firenze_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_roles_users")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("security_roles_users")
    op.drop_table("security_role")
    # ### end Alembic commands ###
