"""Feria

Revision ID: 82c359d6a28d
Revises: 9e62063519e5
Create Date: 2023-06-21 02:25:08.488852

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "82c359d6a28d"
down_revision = "9e62063519e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("comuna", "ferias_comuna")
    op.rename_table("feria", "ferias_feria")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("ferias_comuna", "comuna")
    op.rename_table("ferias_feria", "feria")
    # ### end Alembic commands ###
