"""Feria pk

Revision ID: 8afdd4d03364
Revises: 82c359d6a28d
Create Date: 2023-06-21 02:32:03.955996

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8afdd4d03364"
down_revision = "82c359d6a28d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ferias_comuna", schema=None) as batch_op:
        batch_op.drop_constraint("uq_comuna_slug", type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_ferias_comuna_slug"), ["slug"])

    with op.batch_alter_table("ferias_feria", schema=None) as batch_op:
        batch_op.add_column(sa.Column("comuna_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint("uq_feria_slug", type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_ferias_feria_slug"), ["slug"])
        batch_op.create_foreign_key(
            batch_op.f("fk_ferias_feria_comuna_id_ferias_comuna"),
            "ferias_comuna",
            ["comuna_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ferias_feria", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_ferias_feria_comuna_id_ferias_comuna"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("uq_ferias_feria_slug"), type_="unique")
        batch_op.create_unique_constraint("uq_feria_slug", ["slug"])
        batch_op.drop_column("comuna_id")

    with op.batch_alter_table("ferias_comuna", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_ferias_comuna_slug"), type_="unique")
        batch_op.create_unique_constraint("uq_comuna_slug", ["slug"])

    # ### end Alembic commands ###
