"""Ferias y Comunas

Revision ID: 9e62063519e5
Revises: 771a438591c5
Create Date: 2023-06-21 02:08:36.197637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e62063519e5"
down_revision = "771a438591c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comuna",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=True),
        sa.Column("nombre", sa.String(length=64), nullable=True),
        sa.Column("cut", sa.Integer(), nullable=True),
        sa.Column("provincia", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.Column("ubicacion", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comuna")),
        sa.UniqueConstraint("slug", name=op.f("uq_comuna_slug")),
    )
    op.create_table(
        "feria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=True),
        sa.Column("nombre", sa.String(length=64), nullable=True),
        sa.Column("lunes", sa.Boolean(), nullable=True),
        sa.Column("martes", sa.Boolean(), nullable=True),
        sa.Column("miercoles", sa.Boolean(), nullable=True),
        sa.Column("jueves", sa.Boolean(), nullable=True),
        sa.Column("viernes", sa.Boolean(), nullable=True),
        sa.Column("sabado", sa.Boolean(), nullable=True),
        sa.Column("domingo", sa.Boolean(), nullable=True),
        sa.Column("ubicacion", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feria")),
        sa.UniqueConstraint("slug", name=op.f("uq_feria_slug")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feria")
    op.drop_table("comuna")
    # ### end Alembic commands ###
