"""Init

Revision ID: acc25e8c5fba
Revises:
Create Date: 2023-06-25 19:03:37.001930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "acc25e8c5fba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ferias_comuna",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=True),
        sa.Column("nombre", sa.String(length=64), nullable=True),
        sa.Column("cut", sa.Integer(), nullable=True),
        sa.Column("provincia", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.Column("ubicacion", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ferias_comuna")),
        sa.UniqueConstraint("slug", name=op.f("uq_ferias_comuna_slug")),
    )
    op.create_table(
        "firenze_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("fs_uniquifier", sa.String(length=255), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("current_login_ip", sa.String(length=64), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firenze_user")),
        sa.UniqueConstraint("fs_uniquifier", name=op.f("uq_firenze_user_fs_uniquifier")),
        sa.UniqueConstraint("username", name=op.f("uq_firenze_user_username")),
    )
    op.create_table(
        "ferias_feria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=True),
        sa.Column("nombre", sa.String(length=64), nullable=True),
        sa.Column("lunes", sa.Boolean(), nullable=True),
        sa.Column("martes", sa.Boolean(), nullable=True),
        sa.Column("miercoles", sa.Boolean(), nullable=True),
        sa.Column("jueves", sa.Boolean(), nullable=True),
        sa.Column("viernes", sa.Boolean(), nullable=True),
        sa.Column("sabado", sa.Boolean(), nullable=True),
        sa.Column("domingo", sa.Boolean(), nullable=True),
        sa.Column("ubicacion", sa.JSON(), nullable=True),
        sa.Column("comuna_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comuna_id"], ["ferias_comuna.id"], name=op.f("fk_ferias_feria_comuna_id_ferias_comuna")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ferias_feria")),
        sa.UniqueConstraint("slug", name=op.f("uq_ferias_feria_slug")),
    )
    op.create_table(
        "security_roles_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"], ["security_role.id"], name=op.f("fk_security_roles_users_role_id_security_role")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["firenze_user.id"], name=op.f("fk_security_roles_users_user_id_firenze_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_roles_users")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("security_roles_users")
    op.drop_table("ferias_feria")
    op.drop_table("firenze_user")
    op.drop_table("ferias_comuna")
    # ### end Alembic commands ###
